package hermeskanban

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/irootkernel/agent-dispatch/internal/ports"
)

// ProbeContractVersion names the probe contract this build speaks: the
// read-only shape checks below and their parsing rules (ADR-0017,
// HER-012). A record probed under a different contract version is
// stale (HER-013).
const ProbeContractVersion = "agent-dispatch.hermes-probe/v2"

// CapabilityRecordSchema is the cached record's schema identity.
const CapabilityRecordSchema = "agent-dispatch.hermes-capability-evidence/v2"

// CapabilityRecord is the inspectable cached probe evidence: the probe
// inputs it was keyed by (executable path and digest, reported version,
// contract) and the per-shape outcomes. The file is generated by the
// probe — never operator-authored (HER-012).
type CapabilityRecord struct {
	SchemaVersion    string `json:"schema_version"`
	Contract         string `json:"probe_contract"`
	ProbedAt         string `json:"probed_at"`
	ExecutablePath   string `json:"executable_path"`
	ExecutableDigest string `json:"executable_sha256"`
	HermesVersion    string `json:"hermes_version"`
	// Profile records the skill-table scope the record was probed under
	// ("" = unscoped): a cache read with a different scope is stale, so
	// one destination's profile evidence is never served as another's
	// (HER-013 completeness).
	Profile string `json:"profile"`
	// EnabledSkills is the parsed enabled-skill inventory for the
	// probed profile scope (nil when the skill-table shape failed);
	// recorded at probe time so consumers never re-parse the summary
	// detail (E11-T3 preflight).
	EnabledSkills []string    `json:"enabled_skills,omitempty"`
	Shapes        ProbeShapes `json:"shapes"`
	MissingFlags  []string    `json:"missing_create_flags,omitempty"`
	Fingerprint   string      `json:"fingerprint"`
}

// ProbeShapes carries each bounded shape probe's outcome. A shape
// failure names the missing capability for the operator (HER-014).
type ProbeShapes struct {
	Version       ProbeShape `json:"version"`
	AssigneesJSON ProbeShape `json:"assignees_json"`
	ListJSON      ProbeShape `json:"list_json"`
	CreateSurface ProbeShape `json:"create_surface"`
	SkillTable    ProbeShape `json:"skill_table"`
}

// ProbeShape is one probe's bounded outcome.
type ProbeShape struct {
	Ran    bool   `json:"ran"`
	Passed bool   `json:"passed"`
	Detail string `json:"detail,omitempty"`
}

// RequiredCreateFlags are the public create-surface flags the adapter
// may send; their presence is probed from the create help text without
// any side effect. --idempotency-key and --json are unconditional
// (submit_idempotency_key, durable JSON acceptance); the rest gate the
// corresponding optional envelope fields (resource_mutex for
// --mutex-key).
var RequiredCreateFlags = []string{
	"--idempotency-key", "--json", "--body", "--assignee", "--skill",
	"--workspace", "--mutex-key", "--max-runtime", "--max-retries",
	"--priority", "--created-by",
}

// Prober runs the bounded public-interface probe set for one hermes
// target (ADR-0017): version discovery and eligibility, the read-only
// kanban JSON shapes (assignees, list), the create-surface flag
// contract parsed from its help text, and the profile-scoped skill
// table under a fixed rendering environment (SEC-014). Every probe is
// read-only; no task is created and no Hermes state is touched
// (BND-003, HER-010).
type Prober struct {
	client  *Client
	board   string
	profile string
}

// NewProber builds the prober for one target's board; profile may be
// empty, in which case the skill-table probe runs unscoped (the
// preflight path always names the destination's profile).
func NewProber(targetID, executable, minimumVersion, board, profile string, limits ProcessLimits) (*Prober, error) {
	if board == "" {
		return nil, fmt.Errorf("target %s: the probe requires the board slug", targetID)
	}
	if _, err := ParseMinimumVersion(minimumVersion); err != nil {
		return nil, fmt.Errorf("target %s: %w", targetID, err)
	}
	return &Prober{client: NewClient(executable, limits), board: board, profile: profile}, nil
}

// Probe runs every shape probe and assembles the record. A shape
// failure does not abort the run: the record carries every outcome so
// the operator sees the complete picture with the named failures.
func (p *Prober) Probe(ctx context.Context) (*CapabilityRecord, error) {
	rec := &CapabilityRecord{
		SchemaVersion:  CapabilityRecordSchema,
		Contract:       ProbeContractVersion,
		ProbedAt:       time.Now().UTC().Format(time.RFC3339),
		ExecutablePath: p.client.runner.executable,
		Profile:        p.profile,
	}
	digest, err := ExecutableDigest(p.client.runner.executable)
	if err != nil {
		return nil, fmt.Errorf("executable digest: %w", err)
	}
	rec.ExecutableDigest = digest

	// P1: version discovery and the frozen first-line contract.
	version, verr := p.client.DiscoverVersion(ctx)
	if verr != nil {
		rec.Shapes.Version = ProbeShape{Ran: true, Detail: truncate(verr.Error(), diagnosticBound)}
	} else {
		rec.HermesVersion = version.String()
		rec.Shapes.Version = ProbeShape{Ran: true, Passed: true, Detail: version.String()}
	}

	// P2: assignees JSON shape (name + on_disk per entry).
	if assignees, aerr := p.client.Assignees(ctx, p.board); aerr != nil {
		rec.Shapes.AssigneesJSON = ProbeShape{Ran: true, Detail: truncate(aerr.Error(), diagnosticBound)}
	} else {
		rec.Shapes.AssigneesJSON = ProbeShape{Ran: true, Passed: true, Detail: fmt.Sprintf("%d assignees", len(assignees))}
	}

	// P3: list JSON shape (id per entry).
	if tasks, lerr := p.client.List(ctx, p.board, ListOptions{}); lerr != nil {
		rec.Shapes.ListJSON = ProbeShape{Ran: true, Detail: truncate(lerr.Error(), diagnosticBound)}
	} else {
		rec.Shapes.ListJSON = ProbeShape{Ran: true, Passed: true, Detail: fmt.Sprintf("%d tasks", len(tasks))}
	}

	// P4: the create-surface flag contract from the help text. A
	// missing --mutex-key downgrades resource_mutex (the renderer
	// suppresses the key); any other missing flag fails the shape.
	missing, cerr := p.probeCreateSurface(ctx)
	switch {
	case cerr != nil:
		rec.Shapes.CreateSurface = ProbeShape{Ran: true, Detail: truncate(cerr.Error(), diagnosticBound)}
	case len(missing) > 0:
		rec.MissingFlags = missing
		rec.Shapes.CreateSurface = ProbeShape{Ran: true, Passed: onlyMutexMissing(missing), Detail: "missing create flags: " + strings.Join(missing, ", ")}
	default:
		rec.Shapes.CreateSurface = ProbeShape{Ran: true, Passed: true, Detail: "required create flags present"}
	}

	// P5: the skill table under the fixed rendering environment.
	if skills, serr := p.probeSkillTable(ctx); serr != nil {
		rec.Shapes.SkillTable = ProbeShape{Ran: true, Detail: truncate(serr.Error(), diagnosticBound)}
	} else {
		// A passing table always records a non-nil inventory (possibly
		// empty), so an absent field unambiguously means the shape
		// failed — never a healthy zero-skill table.
		enabled := []string{}
		for _, row := range skills {
			if row.Enabled() {
				enabled = append(enabled, row.Name)
			}
		}
		sort.Strings(enabled)
		rec.EnabledSkills = enabled
		rec.Shapes.SkillTable = ProbeShape{Ran: true, Passed: true, Detail: fmt.Sprintf("%d enabled skills", len(skills))}
	}

	rec.Fingerprint = rec.computeFingerprint()
	return rec, nil
}

// probeCreateSurface parses the create subcommand's help text for the
// required flags — a read-only shape probe that catches interface
// drift (for example a release dropping --mutex-key) before any task
// is created.
func (p *Prober) probeCreateSurface(ctx context.Context) ([]string, error) {
	res, err := p.client.runner.run(ctx, p.client.runner.limits.LookupTimeout,
		[]string{"kanban", "--board", p.board, "create", "-h"})
	if err != nil {
		return nil, fmt.Errorf("create help: %w", err)
	}
	help := string(res.Stdout)
	var missing []string
	for _, flag := range RequiredCreateFlags {
		if !strings.Contains(help, flag) {
			missing = append(missing, flag)
		}
	}
	return missing, nil
}

// probeSkillTable runs the profile-scoped skill list under the fixed
// rendering environment and parses the table fail-closed (SEC-014).
func (p *Prober) probeSkillTable(ctx context.Context) ([]SkillRow, error) {
	argv := []string{"skills", "list", "--enabled-only"}
	if p.profile != "" {
		argv = []string{"-p", p.profile, "skills", "list", "--enabled-only"}
	}
	fixed := *p.client.runner
	fixed.fixedEnv = true
	res, err := fixed.run(ctx, fixed.limits.LookupTimeout, argv)
	if err != nil {
		return nil, fmt.Errorf("skills list: %w", err)
	}
	return ParseSkillTable(string(res.Stdout))
}

// computeFingerprint derives the capability-evidence fingerprint over
// the schema, probe contract, executable identity, and version
// (HER-013/HER-018: any change invalidates). The shape outcomes are a
// pure function of these inputs — the same executable bytes under the
// same contract probe identically — so the submit path can re-prove
// the fingerprint from the live identity without re-running every
// shape probe.
func (r *CapabilityRecord) computeFingerprint() string {
	return DeriveFingerprint(r.SchemaVersion, r.Contract, r.ExecutablePath, r.ExecutableDigest, r.HermesVersion)
}

// DeriveFingerprint is the one capability-evidence fingerprint
// derivation (HER-013/HER-018): the activation binding and the
// submit-time re-proof both call it, so they can never drift apart.
func DeriveFingerprint(schema, contract, executablePath, executableDigest, hermesVersion string) string {
	sum := sha256.Sum256([]byte(strings.Join([]string{
		schema, contract, executablePath, executableDigest, hermesVersion,
	}, "\x00")))
	return "cap:" + hex.EncodeToString(sum[:16])
}

// AllRequiredPassed reports whether every capability-relevant probed
// shape passed (the skill table is preflight evidence, not a
// capability gate).
func (r *CapabilityRecord) AllRequiredPassed() bool {
	return r.Shapes.Version.Passed && r.Shapes.AssigneesJSON.Passed &&
		r.Shapes.ListJSON.Passed && r.Shapes.CreateSurface.Passed
}

// Capabilities maps the probed shapes onto the port capability set
// (HER-005 posture under the probe contract): the JSON machinery plus
// the unconditional create-surface flags prove the delivery evidence;
// --mutex-key alone gates resource_mutex — its absence downgrades the
// mutex capability (the renderer then suppresses the key) rather than
// failing the target.
func (r *CapabilityRecord) Capabilities() (ports.Capabilities, error) {
	if !r.AllRequiredPassed() {
		if len(r.MissingFlags) > 0 {
			return ports.Capabilities{}, fmt.Errorf("the create surface lacks %s; this build cannot submit the configured envelope; run 'agent-dispatch hermes probe' and inspect the named failures", strings.Join(r.MissingFlags, ", "))
		}
		return ports.Capabilities{}, fmt.Errorf("capability evidence incomplete: version=%t assignees_json=%t list_json=%t create_surface=%t; run 'agent-dispatch hermes probe' and resolve the named failures",
			r.Shapes.Version.Passed, r.Shapes.AssigneesJSON.Passed, r.Shapes.ListJSON.Passed, r.Shapes.CreateSurface.Passed)
	}
	for _, flag := range r.MissingFlags {
		if flag != "--mutex-key" {
			return ports.Capabilities{}, fmt.Errorf("the create surface lacks %s; this build cannot submit the configured envelope", flag)
		}
	}
	return ports.Capabilities{
		DurableAcceptance:    true,
		SubmitIdempotencyKey: true,
		LookupByExternalRef:  true,
		ResourceMutex:        !containsString(r.MissingFlags, "--mutex-key"),
		ExecutionStatus:      true,
	}, nil
}

func containsString(list []string, want string) bool {
	for _, s := range list {
		if s == want {
			return true
		}
	}
	return false
}

// onlyMutexMissing reports whether every missing create flag is the
// mutex key — the one whose absence downgrades a capability instead of
// failing the target.
func onlyMutexMissing(missing []string) bool {
	for _, flag := range missing {
		if flag != "--mutex-key" {
			return false
		}
	}
	return true
}

// ExecutableDigest hashes the executable file's exact bytes — the
// identity half of the cache key (HER-013). A PATH-relative name
// resolves through exec.LookPath first, exactly as invocation does, so
// "hermes" digests the binary that would run.
func ExecutableDigest(path string) (string, error) {
	if path == "" {
		return "", fmt.Errorf("executable path is empty")
	}
	resolved := path
	if !filepath.IsAbs(resolved) {
		found, err := exec.LookPath(resolved)
		if err != nil {
			return "", err
		}
		resolved = found
	}
	raw, err := os.ReadFile(resolved)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(raw)
	return "sha256:" + hex.EncodeToString(sum[:]), nil
}

// LoadCapabilityRecord reads a cached record.
func LoadCapabilityRecord(path string) (*CapabilityRecord, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("capability evidence %s: %w", path, err)
	}
	var rec CapabilityRecord
	if err := json.Unmarshal(raw, &rec); err != nil {
		return nil, fmt.Errorf("capability evidence %s: %w", path, err)
	}
	if rec.SchemaVersion != CapabilityRecordSchema {
		return nil, fmt.Errorf("capability evidence %s: schema %q is not the v2 probe record", path, rec.SchemaVersion)
	}
	return &rec, nil
}

// StaleReason returns "" when the record may authorize this executable
// identity, or the bounded reason it may not (HER-013: executable
// path, digest, version, or probe-contract change). A non-empty
// wantedProfile also requires the record's skill-table scope to match.
func (r *CapabilityRecord) StaleReason(executablePath, executableDigest, hermesVersion string) string {
	return r.StaleReasonForProfile(executablePath, executableDigest, hermesVersion, "")
}

// StaleReasonForProfile is StaleReason with the skill-table scope in
// hand: profile-scoped evidence cannot authorize a different profile.
func (r *CapabilityRecord) StaleReasonForProfile(executablePath, executableDigest, hermesVersion, wantedProfile string) string {
	switch {
	case r.Contract != ProbeContractVersion:
		return fmt.Sprintf("probed under contract %q, this build speaks %q; re-run the probe", r.Contract, ProbeContractVersion)
	case r.ExecutablePath != executablePath:
		return fmt.Sprintf("probed for executable %q, now %q", r.ExecutablePath, executablePath)
	case r.ExecutableDigest != executableDigest:
		return "the executable changed since the probe; re-run the probe"
	case hermesVersion != "" && r.HermesVersion != hermesVersion:
		return fmt.Sprintf("probed against hermes %s, now %s", r.HermesVersion, hermesVersion)
	case wantedProfile != "" && r.Profile != wantedProfile:
		return fmt.Sprintf("probed with skill-table scope %q, wanted %q; re-run the probe for the destination's profile", scopeLabel(r.Profile), wantedProfile)
	}
	return ""
}

func scopeLabel(profile string) string {
	if profile == "" {
		return "unscoped"
	}
	return profile
}

// WriteCapabilityRecord persists the record atomically with
// owner-only permissions.
func WriteCapabilityRecord(rec *CapabilityRecord, path string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	data, err := json.MarshalIndent(rec, "", "  ")
	if err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, ".hermes-capability-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(append(data, '\n')); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}

// EnabledSkillNames returns the sorted enabled-skill inventory the
// skill-table probe recorded, or nil when the skill-table shape did
// not pass (the preflight path then fails closed on its own check).
func (r *CapabilityRecord) EnabledSkillNames() []string {
	if !r.Shapes.SkillTable.Passed {
		return nil
	}
	if r.EnabledSkills == nil {
		return []string{}
	}
	return append([]string(nil), r.EnabledSkills...)
}

// CapabilitiesIncludeMutex reports whether the probed create surface
// carries --mutex-key (the resource_mutex capability).
func (r *CapabilityRecord) CapabilitiesIncludeMutex() bool {
	caps, err := r.Capabilities()
	return err == nil && caps.ResourceMutex
}
