package hermeskanban

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/irootkernel/agent-dispatch/internal/ports"
)

// ReportSchemaVersion is the frozen capability-report document version
// (schemas/hermes-capability-report.schema.json).
const ReportSchemaVersion = "agent-dispatch.hermes-capabilities/v1"

// ReportError is a persistent configuration defect in the capability
// report itself: unreadable, wrong schema, wrong interface, or probed
// against a different Hermes version than the installation. The
// validation surface fails closed on it (exit 3), distinct from a
// transiently unreachable target.
type ReportError struct {
	Detail string
}

func (e *ReportError) Error() string {
	return "capability report defect: " + e.Detail
}

// Report is the typed E0-T4 capability report. It is generated by the
// public-interface probe, contains no secrets, and is the only capability
// authority (configuration-spec §5).
type Report struct {
	SchemaVersion string            `json:"schema_version"`
	ProbedAt      string            `json:"probed_at"`
	HermesVersion string            `json:"hermes_version"`
	Interface     string            `json:"interface"`
	Capabilities  map[string]bool   `json:"capabilities"`
	Limits        ReportLimits      `json:"limits"`
	Evidence      []json.RawMessage `json:"evidence"`
	Notes         []string          `json:"notes"`
}

// ReportLimits carries the measured target limits; a null
// maximum_request_bytes means Hermes documents no public request-size
// limit and the adapter enforces its own bound (E0-T4 §8 note).
type ReportLimits struct {
	MaximumRequestBytes *int64 `json:"maximum_request_bytes"`
}

// LoadReport reads and validates one capability report. It fails closed
// on the wrong schema version or interface and on a non-object document.
func LoadReport(path string) (*Report, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, &ReportError{Detail: fmt.Sprintf("cannot read %s: %v", path, err)}
	}
	var doc Report
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, &ReportError{Detail: fmt.Sprintf("%s is not valid JSON: %v", path, truncate(err.Error(), 200))}
	}
	if doc.SchemaVersion != ReportSchemaVersion {
		return nil, &ReportError{Detail: fmt.Sprintf("%s has schema version %q, want %q", path, doc.SchemaVersion, ReportSchemaVersion)}
	}
	if doc.Interface != "public_cli" {
		return nil, &ReportError{Detail: fmt.Sprintf("%s documents interface %q; the kanban adapter requires public_cli", path, doc.Interface)}
	}
	if doc.HermesVersion == "" {
		return nil, &ReportError{Detail: fmt.Sprintf("%s records no hermes_version", path)}
	}
	return &doc, nil
}

// PortCapabilities maps the report onto the sink port capability set
// (HER-004) through the single name↔field mapping on
// ports.Capabilities. A capability absent from the report is false: the
// report is the whole truth and nothing is assumed beyond it (HER-002).
func (r *Report) PortCapabilities() ports.Capabilities {
	m := ports.Capabilities{}.BoolMap()
	for _, name := range ports.CapabilityNames {
		m[name] = r.Capabilities[name]
	}
	caps := ports.CapabilitiesFromBoolMap(m)
	if r.Limits.MaximumRequestBytes != nil {
		caps.MaximumRequestBytes = *r.Limits.MaximumRequestBytes
	}
	return caps
}

// recordedTriple returns the dotted-triple prefix of the report's
// hermes_version field ("0.19.1 (2026.7.30)" → "0.19.1"); the triple is
// the identity both freshness and support comparisons use.
func (r *Report) recordedTriple() string {
	recorded := r.HermesVersion
	if i := strings.IndexByte(recorded, ' '); i >= 0 {
		recorded = recorded[:i]
	}
	return recorded
}

// VersionMatchsWith reports whether the report was probed against the
// discovered installed version (configuration-spec: capability-report
// freshness against the installed target). The report's hermes_version
// field is the full first-line text; the dotted triple must prefix it.
func (r *Report) VersionMatchsWith(v Version) bool {
	return r.recordedTriple() == v.String()
}

// RecordedVersionSupported reports whether the report's recorded
// hermes_version triple is one of the runtime-verified supported
// versions (E0-T4 §10). It needs no live target — the supported set is
// build-time evidence — so the enable gate can refuse a report probed
// against an unsupported Hermes even while the executable is
// unreachable (E9-T6).
func (r *Report) RecordedVersionSupported() bool {
	for _, s := range SupportedVersions {
		if r.recordedTriple() == s.String() {
			return true
		}
	}
	return false
}

// ValidateRequired checks the required capability names against actual
// capabilities (HER-005). An unknown name fails closed: it is a
// configuration defect, not a reduced guarantee. A missing capability is
// a validation error; silent emulation is never an option.
func ValidateRequired(targetID string, caps ports.Capabilities, required []string) error {
	known := caps.BoolMap()
	var unknown, missing []string
	for _, name := range required {
		have, ok := known[name]
		if !ok {
			unknown = append(unknown, name)
			continue
		}
		if !have {
			missing = append(missing, name)
		}
	}
	if len(unknown) > 0 {
		return &InvalidRequirementError{TargetID: targetID, Unknown: unknown}
	}
	if len(missing) > 0 {
		return &CapabilityError{TargetID: targetID, Missing: missing}
	}
	return nil
}
